# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -U pip setuptools wheel \
 && pip install --no-cache-dir .

EXPOSE 8080

CMD ["python", "server.py", "--transport", "http", "--host", "0.0.0.0", "--port", "8080", "--path", "/mcp"]
