# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install system dependencies
WORKDIR /app

# Install build tools and your package (reads pyproject.toml)
COPY pyproject.toml setup.py* /app/
RUN pip install --no-cache-dir wheel setuptools \
 && pip install --no-cache-dir .

# Copy the rest of your code
COPY . /app

# Expose the HTTP-Stream port that your server uses (/mcp)
EXPOSE 8080

# Start the server in HTTP-Stream mode on /mcp
CMD ["python", "server.py", "--transport", "http", "--host", "0.0.0.0", "--port", "8080", "--path", "/mcp"]

